
name: Build Armbian

on:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - '.armbian.config'
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: started

env:
  REPO_URL: https://github.com/Leo357449107/Build-Armbian
  REPO_BRANCH: 20.11
  REPO_COMMIT: 7823483f39d4c4e877b4af70365cda28a33f55e3
  CONFIG_FILE: .armbian.config

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone source code
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH armbian

    - name: Compile the firmware
      id: compile
      run: |
        cd armbian
        touch param.sh
        [ -e $CONFIG_FILE ] && cat $CONFIG_FILE > param.sh
        cat param.sh
        ./compile.sh `cat param.sh`
        tar -cJvf armbian.tar.xz output
        echo "::set-output name=status::success"
        
    - name: Upload armbian firmware
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: Armbian_Build_Output
        path: armbian/armbian.tar.xz

